In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
arr3=np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [5]:
arr5=np.dstack((arr1,arr2))
print(arr5)

[[[1 4]
  [2 5]
  [3 6]]]


In [6]:
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
print(arr[0])
print(arr[1])
print(arr[2])

1
2
3
